blueprint:
  name: Fyrtur control open/close remote (Midea U AC version)
  description: |
    Control a cover with an Ikea Tradfri open/close button remote over ZHA

    Short press on ☼ button will open the cover.
    Short press on ☰ button will close the cover.
    Long press on ☼ or ☰  will stop the cover.
  domain: automation
  input:
    remote:
      name: Remote
      description: "IKEA open/close remote to use"
      selector:
        device:
          integration: zha
          manufacturer: "\x02KE"
          model: "TRADFRI open/close remote"
    cover:
      name: Cover
      description: The cover to control
      selector:
        target:
          entity:
            domain: cover
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- choose:
  - conditions:
    - '{{ trigger.event.data.command == "up_open" }}'
    sequence:
    - service: cover.set_cover_position
      target: !input cover
      data:
        position: 50
  - conditions:
    - '{{ trigger.event.data.command == "down_close" }}'
    sequence:
    - service: cover.close_cover
      target: !input cover
  - conditions:
    - '{{ trigger.event.data.command in ("stop", "stop_opening", "stop_closing") }}'
    sequence:
    - service: cover.set_cover_position
      target: !input cover
      data:
        position: 95
mode: restart